minor change in build-nightly: build only of configure has not failed, build docs and tests only if build has not failed.
git-svn-id: https://bioproj.extra.cea.fr/neurosvn/brainvisa/development/brainvisa-cmake/branches/bug_fix@71820 613412ce-1361-4b7a-93bf-a3c75af1bae4

diff --git a/bin/bv_build_nightly b/bin/bv_build_nightly
--- a/bin/bv_build_nightly
+++ b/bin/bv_build_nightly
@@ -224,10 +224,13 @@ if [ $os != "windows" ];then
   find `dirname $binary_dir` -name '*.pyc' -exec rm "{}" \; -or -name '*.pyo' -exec rm "{}" \;
 fi
 
-bv_configure
-bv_build
-bv_doc
-bv_test
+bv_configure && bv_build
+ok=$?
+# don't run doc and test if build has failed
+if [ $ok = "0" ]; then
+  bv_doc
+  bv_test
+fi
 
 echo "End compile and doc "
 
